[tool.poetry]
name = "whisper-compose"
version = "0.1.0"
description = ""
authors = ["Yaroslav Orlov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai-whisper = "20250625"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
